---
- name: Setup services machine
  hosts: services_hosts
  gather_facts: no
  tasks:
    - name: Include apache installation playbook
      include_tasks: playbooks/install_apache.yaml

    - name: Include bind installation playbook
      include_tasks: playbooks/install_bind.yaml

    - name: Copy bind server configuration files
      ansible.builtin.copy:
        src: /tmp/bind/
        dest: /etc/bind/
