---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install Bind package
  apt:
    name: bind9
    state: present

- name: Ensure Named service is running and enabled
  service:
    name: named
    state: started
    enabled: yes
