---
- name: Install Apache web server
  hosts: services_hosts
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
