---
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install Apache package
  become: true
  apt:
    name: apache2
    state: present

- name: Ensure Apache service is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
